package com.xiaoyv.blueprint.constant

object NavKey {
    const val KEY_STRING = "String"
    const val KEY_STRING_SECOND = "StringSecond"
    const val KEY_STRING_THIRD = "StringThird"
    const val KEY_INTEGER = "Integer"
    const val KEY_INTEGER_SECOND = "IntegerSecond"
    const val KEY_INTEGER_THIRD = "IntegerThird"
    const val KEY_LONG = "Long"
    const val KEY_LONG_SECOND = "LongSecond"
    const val KEY_LONG_THIRD = "LongThird"
    const val KEY_FLOAT = "Float"
    const val KEY_FLOAT_SECOND = "FloatSecond"
    const val KEY_FLOAT_THIRD = "FloatThird"
    const val KEY_DOUBLE = "Double"
    const val KEY_DOUBLE_SECOND = "DoubleSecond"
    const val KEY_DOUBLE_THIRD = "DoubleThird"
    const val KEY_SERIALIZABLE = "Serializable"
    const val KEY_SERIALIZABLE_ARRAY = "SerializableArray"
    const val KEY_SERIALIZABLE_SECOND = "SerializableSecond"
    const val KEY_SERIALIZABLE_THIRD = "SerializableThird"
    const val KEY_BOOLEAN = "Boolean"
    const val KEY_BOOLEAN_SECOND = "BooleanSecond"
    const val KEY_BOOLEAN_THIRD = "BooleanThird"
    const val KEY_PARCELABLE = "Parcelable"
    const val KEY_PARCELABLE_LIST = "ParcelableList"
    const val KEY_PARCELABLE_ARRAY = "ParcelableArray"
    const val KEY_PARCELABLE_SECOND = "ParcelableSecond"
    const val KEY_PARCELABLE_THIRD = "ParcelableThird"
    const val KEY_BINDER = "Binder"
}